name: Update universes

on:
  schedule:
    # this should run right after most of harvesting is finished on data.gouv.fr
    - cron: "4 5 * * *"
  workflow_dispatch:

jobs:
  run-update:
    runs-on: ubuntu-latest
    concurrency:
      # TODO: enable concurrency? make sure git commits don't step on eachother
      group: no_concurrency
      cancel-in-progress: false
    strategy:
      fail-fast: false
      # max-parallel=1 as workaround to preserve matrix execution order
      # https://github.com/actions/runner/issues/703
      max-parallel: 1
      matrix:
        universe:
          - culture-prod
          - culture-deps-prod
          - ecospheres-demo
          - ecospheres-prod
          - accessibilite-demo
          - accessibilite-prod
    environment: ${{ matrix.universe }}
    env:
      ARTIFACTS_BRANCH: artifacts
      ARTIFACTS_DIRS: dist logs
      CONFIG_FILE: configs/${{ matrix.universe }}.yaml
      LOG_FILE: logs/${{ matrix.universe }}.log

    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install dependencies
        run: uv sync

      - name: Ensure clean artifact dirs
        run: |
          rm -rf ${{ env.ARTIFACTS_DIRS }}
          mkdir ${{ env.ARTIFACTS_DIRS }}

      - name: Update ${{ matrix.universe }} universe
        env:
          DATAGOUV_API_KEY: ${{ secrets.DATAGOUV_API_KEY  }}
          GRIST_API_KEY: ${{ secrets.GRIST_API_KEY }}
          PYTHONUNBUFFERED: 1
        run: |
          uv run universe feed-universe ${{ env.CONFIG_FILE }} --fail-on-errors 2>&1 | tee ${{ env.LOG_FILE }}
          exit ${PIPESTATUS[0]}

      - name: Create artifacts worktree
        id: create-worktree
        env:
          ARTIFACTS_WORKTREE: ${{ runner.temp }}/${{ env.ARTIFACTS_BRANCH }}-worktree
        run: |
          git fetch origin ${{ env.ARTIFACTS_BRANCH }}
          git worktree add --track -b ${{ env.ARTIFACTS_BRANCH }} $ARTIFACTS_WORKTREE origin/${{ env.ARTIFACTS_BRANCH }}
          echo "ARTIFACTS_WORKTREE=${{ env.ARTIFACTS_WORKTREE }}" >> $GITHUB_ENV

      - name: Commit artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp -a ${{ env.ARTIFACTS_DIRS }} $ARTIFACTS_WORKTREE
          pushd $ARTIFACTS_WORKTREE
          git add ${{ env.ARTIFACTS_DIRS }}
          git commit --no-verify -m "workflow: update daily run for ${{ matrix.universe }}"
          git pull --rebase origin ${{ env.ARTIFACTS_BRANCH }}
          git push
          popd

      - name: Delete worktree
        if: always() && steps.create-worktree.outcome == 'success'
        run: git worktree remove -f $ARTIFACTS_WORKTREE
